import { useState, useEffect } from 'react'
import PokeCard from '../components/PokeCard'
import '../style.css'

// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface Page {
	count:    number;
	next:     string;
	previous: null;
	results:  Result[];
}

export interface Result {
	name: string;
	url:  string;
}

export interface Pokemon {
	id:                       number;
	name:                     string;
	//order:                    number;
	sprites:                  Sprites;
	types:                    Type[];
}

export interface Species {
	name: string;
	url:  string;
}

export interface Sprites {
	// back_default:       string;
	// back_female:        null;
	// back_shiny:         string;
	// back_shiny_female:  null;
	front_default:      string;
	// front_female:       null;
	// front_shiny:        string;
	// front_shiny_female: null;
	// animated?:          Sprites;
}

export interface Type {
	slot: number;
	type: Species;
}




function PokeDashboard() {
	const [pokemons, setPokemons] = useState<Pokemon[]>([]);
	//const [page, setPage] = useState<Page>();
	const [pageOffset, setPageOffset] = useState<number>(0);
	const [isLoading, setIsLoading] = useState<boolean>(false);
	const limit = 21;

	useEffect(() => {
		const controller = new AbortController();
		const signal = controller.signal;

		async function fetchPokemons() {
		let details: any[] = [];
		setIsLoading(true);

		try {
			const res = await fetch(
				`https://pokeapi.co/api/v2/pokemon/?offset=${pageOffset}&limit=${limit}/`,
				{ signal }
				);

			if (!res.ok) throw new Error ("Data not found")
			const data : Page = await res.json();
			//setPage(data);

			details = await Promise.all(
				data.results.map(async (p: any) => {
					const res = await fetch(p.url, { signal }) ;
					return await res.json();
				})
			);
			setPokemons(details);
			} catch (error : any) {
				if (error.name === "AbortError") {
					console.log("Fetch aborted")
				} else {
					console.error(error)
				} 
			} finally {
				setIsLoading(false);
			} 
		}
		fetchPokemons();

		return () => {
			controller.abort();
		};
	},[pageOffset]);
	
	return (
		<>
		<nav className="pokemonPaging"> 
			{<button disabled={pageOffset <= 0} onClick={() => setPageOffset(pageOffset - limit)}>Anterior</button>}
			<button onClick={() => setPageOffset(pageOffset + limit)}>Siguiente</button>
		</nav>
		<section className="pokemonDashboard"> 
		<div className="pokemonDashboard__filter">
				<input id="pokemonFilter" type="text" placeholder="Filtrar pokemons por nombre..."/>
		</div>
		{pokemons.map(({id, name, types, sprites}) => ( 
			<PokeCard 
				id={id} 
				name={name}
				types={types.map((t: any) => t.type.name)} 
				img={sprites.front_default} 
			/>) )}
		{/* <PokeCard id={1} name="Bulbasaur" types={["Grass", "Poison"]} img="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png" /> */}
		</section>
		<nav className="pokemonPaging"> 
			{<button disabled={pageOffset <= 0} onClick={() => setPageOffset(pageOffset - limit)}>Anterior</button>}
			<button onClick={() => setPageOffset(pageOffset + limit)}>Siguiente</button>
		</nav>
		</>

		
	)
}

export default PokeDashboard
